In [1]:
import numpy as np

In [2]:
def decoratorr():
    print('*******************')

In [3]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
#2d numpy

a=np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [5]:
#3d numpy

a=np.array([[[1,2],[2,3]],[[3,4],[4,5]]])
print(a)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]


In [6]:
# dtype

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
# reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
# np.zeros/np.ones

print(np.zeros((5,2)))
decoratorr()
print(np.ones((5,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
*******************
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# raandom.random

np.random.random((3,2)) # 0-1

array([[0.58232713, 0.97070288],
       [0.51086197, 0.75591382],
       [0.80973137, 0.20485139]])

In [14]:
# linespace(linear space)
np.linspace(1,10,3) #(lower,upper,no. of items)

array([ 1. ,  5.5, 10. ])

In [17]:
# identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [19]:
a1 = np.arange(10,dtype=np.int32) # vector
a2 = np.arange(12,dtype=float).reshape(3,4)# metrix
a3 = np.arange(8).reshape(2,2,2)#tensor

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
#ndim
np.ndim(a2)

2

In [23]:
a2.ndim

2

In [ ]:
#shape
np.shape(a3)

(2, 2, 2)

In [27]:
a3.shape

(2, 2, 2)

In [28]:
#size
np.size(a3)

8

In [29]:
a3.size

8

In [33]:
# itemsize
print(a3.itemsize)
print(a2.itemsize)
print(a1.itemsize) # based on dtype

8
8
4


In [34]:
#dtype
a1.dtype

dtype('int32')

## change in dtype

In [35]:
#astype

a3.dtype

dtype('int64')

In [36]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operation

In [37]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
# scaler operation
# arithmatical

a2 + 2

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [40]:
# relational

a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [41]:
# vector operation
# arithmatic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array function

In [42]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[13., 11., 84.],
       [77., 24., 52.],
       [96., 83.,  0.]])

In [46]:
# max/min/sum/prod
# 0 -> col and 1 -> row

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))

96.0
0.0
440.0


In [47]:
print(np.max(a1,axis=0))
print(np.min(a1,axis=1))
print(np.sum(a1,axis=0))

[96. 83. 84.]
[11. 24.  0.]
[186. 118. 136.]


In [48]:
# mean/median/std/var
print(np.mean(a1,axis=0))
print(np.median(a1,axis=1))
print(np.std(a1,axis=0))
print(np.var(a2,axis=1))

[62.         39.33333333 45.33333333]
[13. 52. 83.]
[35.50586806 31.32978703 34.61534663]
[1.25 1.25 1.25]


In [49]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.42016704, -0.99999021,  0.73319032],
       [ 0.99952016, -0.90557836,  0.98662759],
       [ 0.98358775,  0.96836446,  0.        ]])

In [50]:
# dot product/ multiplication
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [51]:
# log and exponents
np.exp(a1)

array([[4.42413392e+05, 5.98741417e+04, 3.02507732e+36],
       [2.75851345e+33, 2.64891221e+10, 3.83100800e+22],
       [4.92345829e+41, 1.11286375e+36, 1.00000000e+00]])

In [53]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[62., 98., 16.],
       [50., 46.,  4.]])

## Indexing and Slicing

In [54]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a1[-1]

np.int64(9)

In [57]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
print(a2[1,1])

5


In [60]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [62]:
# 5

print(a3[1,0,1])

5


In [63]:
# array([[[0, 1],
#         [2, 3]],------------>0(2D)

#        [[4, 5],
#         [6, 7]]])------------1(2D)

### Slicing

In [64]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# 2, 3, 4, 5
a1[2:6]

array([2, 3, 4, 5])

In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
#  0,  1,  2,  3
a2[0,:]

array([0, 1, 2, 3])

In [70]:
# 1,5,9

a2[:,1]

array([1, 5, 9])

In [71]:
# 5,6
# 9,10

a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [76]:
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [77]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [78]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [83]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
# 3,  4,  5
a3[0,1,:]

array([3, 4, 5])

In [86]:
# 10,13,16

a3[1,:,1]

array([10, 13, 16])

In [87]:
# 22,23
# 25,26

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [88]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
# 0,2
#18,20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [94]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [95]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [96]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [98]:
for i in np.nditer(a3): # convert 3d to 1d
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Re-shaping

In [99]:
# reshape

np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [102]:
# Transpose
print(a2)
print(a2.shape)
decoratorr()
b=np.transpose(a2)
print(b)
print(b.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
*******************
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [103]:
#ravel (convert any dimentionl to 1d array)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [104]:
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [109]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a4.shape)
decoratorr()
print(a5)
print(a5.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
*******************
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(3, 4)


In [110]:
s=np.hstack((a4,a5))
print(s)
print(s.shape)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
(3, 8)


In [111]:
t=np.vstack((a4,a5))
print(t)
print(t.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(6, 4)
