In [1]:
print('sadab')

sadab


In [2]:
['tejaswini' for i in range(1,11)]

['tejaswini',
 'tejaswini',
 'tejaswini',
 'tejaswini',
 'tejaswini',
 'tejaswini',
 'tejaswini',
 'tejaswini',
 'tejaswini',
 'tejaswini']

In [ ]:
# python list/array
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]

c=[]
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
end=time.time()
print(end-start)

1.1763787269592285


In [5]:
# np array
import numpy as np 
a=np.arange(10000000)
b=np.arange(10000000,20000000)

import time
start = time.time()
c= a + b
end=time.time()
print(end-start)

0.11214423179626465


In [7]:
1.1763787269592285/0.11214423179626465

10.489872801450781

NumPy exists because Python alone is too slow

NumPy Is written in C (static array{jiss ka size fixed rehta hai}), it's not referential array{direct is ko memory me stor karte hai na ki iss ka reference}

python -> Dynamic array{size get's double}, it's a referantial array

### but list can store non-homogenius data a = [1, 2.5, "hello", True]


In [8]:
# advanced indexing

a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# fancy indexing
a[[0,2,4,5]] # row

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11],
#        [12, 13, 14, 15],
#        [16, 17, 18, 19],
#        [20, 21, 22, 23]])

In [14]:
a[[2,2,3,3], [1,2,1,2]]

array([ 9, 10, 13, 14])

(2,1) → 9

(2,2) → 10

(3,1) → 13

(3,2) → 14


In [15]:
a[[2,2,4,4],[0,3,0,3]]

array([ 8, 11, 16, 19])

When you use fancy indexing, NumPy returns a 1D array by default.
This is expected behavior, not a mistake.

Best method: use np.ix_()

In [18]:
result = a[np.ix_([2,4],[0,3])]
print(result)

[[ 8 11]
 [16 19]]


(2,0) ->8

(2,3)->11

(4,0)-> 16

(4,3)-> 19

In [19]:
# boolean indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[94, 53, 14, 51],
       [11, 30, 95,  2],
       [12, 59, 93, 62],
       [ 1,  4, 92, 92],
       [26,  1, 32, 37],
       [70, 24, 12, 21]], dtype=int32)

In [20]:
# array([[94, 53, 14, 51],
#        [11, 30, 95,  2],
#        [12, 59, 93, 62],
#        [ 1,  4, 92, 92],
#        [26,  1, 32, 37],
#        [70, 24, 12, 21]], dtype=int32)

In [ ]:
a > 50 # boolean array

array([[ True,  True, False,  True],
       [False, False,  True, False],
       [False,  True,  True,  True],
       [False, False,  True,  True],
       [False, False, False, False],
       [ True, False, False, False]])

In [22]:
a[a>50]

array([94, 53, 51, 95, 59, 93, 62, 92, 92, 70], dtype=int32)

In [23]:
# find out even numbers
a[a % 2 == 0]

array([94, 14, 30,  2, 12, 62,  4, 92, 92, 26, 32, 70, 24, 12],
      dtype=int32)

In [24]:
# find all numbers greater than 50 and are even

a[(a > 50) & (a % 2 == 0)]

array([94, 62, 92, 92, 70], dtype=int32)

In [25]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([94, 53, 51, 11, 30, 95,  2, 12, 59, 93, 62,  1,  4, 92, 92, 26,  1,
       32, 37, 24, 12], dtype=int32)

In [26]:
a[(a % 7 != 0)]

array([94, 53, 51, 11, 30, 95,  2, 12, 59, 93, 62,  1,  4, 92, 92, 26,  1,
       32, 37, 24, 12], dtype=int32)

## Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [27]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [28]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [29]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print('*********')
print(b)
print('*********')
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
*********
[0 1 2]
*********
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [30]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print('*********')
print(b)
print('*********')
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
*********
[0 1 2]
*********


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [31]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print('*********')
print(b)
print('*********')
print(a+b)

[[0 1 2]]
*********
[[0]
 [1]
 [2]]
*********
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [33]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print('*********')
print(b)
print('*********')
print(a+b)

[[0 1 2]]
*********
[[0]
 [1]
 [2]
 [3]]
*********
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [34]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print('*********')
print(b)
print('*********')
print(a+b)

[1]
*********
[[0 1]
 [2 3]]
*********
[[1 2]
 [3 4]]


In [35]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print('*********')
print(b)
print('*********')
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
*********
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
*********


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [36]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print('*********')
print(b)
print('*********')
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
*********
[[0 1]
 [2 3]]
*********


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

In [38]:
a = np.arange(16).reshape(4,4)
b = np.arange(1)

print(a)
print('*********')
print(b)
print('*********')
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
*********
[0]
*********
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Working with mathmatical formula

In [39]:
a=np.arange(10)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [42]:
# sigmoid

def sigmoid(arr):
    return 1/(1 + np.exp(-(arr)))

In [43]:
sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [49]:
actual=np.random.randint(1,10,20)
predict=np.random.randint(1,10,20)

def mse(actual,predict):
    return np.mean((actual - predict)**2)
mse(actual,predict)

np.float64(10.6)

## deals with missing values

In [50]:
# np.nan

a=np.array([1,2,3,4,np.nan,5,6,np.nan])
a

array([ 1.,  2.,  3.,  4., nan,  5.,  6., nan])

In [51]:
np.isnan(a)

array([False, False, False, False,  True, False, False,  True])

In [53]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5., 6.])